### ISSUE TITLE
建议公开GCC源代码

### ISSUE THREAD

**Issue by AnClark** [loongson/build-tools#1]
首先感谢龙芯社区开发者的积极付出，让LoongArch这一新平台也有了属于自己的GCC，为开源社区的持续发展打下了坚实基础。

考虑到GCC是**基于GPL的自由软件**，原则上需要公布修改后的源代码；并且为新架构提供支持，本身就是值得反馈给GNU上游的巨大贡献（龙芯MIPS架构支持已经是GNU官方源码的一部分）。

因此建议龙芯社区团队在此发布源代码，而不仅仅是二进制版本。这样能让更多开发者作出贡献，开启更多新可能。

**Comment by yetist** [comment]
@AnClark

感谢您对龙芯社区和LoongArch的关注，工具链正在为向上游社区提交进行准备中，包括向最新开发分支迁移、测试及整理代码等工作，但是距离上游对代码的规范、质量等各方面的要求还有不少差距，龙芯也愿意尽早开放一版工具链出来，借助社区开发者的力量进行完善，应该用不了太久，就能看到开放出来的工具链源码，也希望包括您在内的社区开发者一起来测试和完善。

谢谢。

**Comment by AnClark** [comment]
也感谢您的解答，期待工具链源码的正式发布。

其实个人愚见，不必等到一切都成熟（可以提交到上游的程度）才发布，至少可以将当前这版发布出来。我打算尝试构建出可在Windows下运行的交叉编译器版本。

---

顺便询问一下LoongArch版**Binutils**的源码能否先发布。

**Comment by FreeFlyingSheep** [comment]
https://github.com/loongson/gcc/tree/loongarch-12
https://github.com/loongson/binutils-gdb/tree/loongarch-2_37
https://github.com/loongson/glibc/tree/loongarch_2_33
