### ISSUE TITLE
loongarch64-clfs-system-2021-12-02在LM3a5000上起不来

### ISSUE THREAD

**Issue by phorcys** [loongson/build-tools#11]
kernel 载入后键盘灯闪一下卡死
拿掉 acpi_initrd 也起不来
启动参数带 verbose ignore_loglevel 也没提示
接上串口 consoleblank=0 earlyprintk=ttyS0 console=ttyS0 nomodeset 串口也没信息

主板：LM-LS3A5000-7A1000-1w-V01-pc_A2101
固件:  
	Vendor: ZD-TECH
	Version: KL.4.1H.LM.D.025.211109.R
	Release Date: 11/09/2021
	ROM Size: 8192 kB

**Comment by FreeFlyingSheep** [comment]
串口参数改成 `earlycon=uart,mmio,0x1fe001e0,115200n8 console=ttyS0,115200` 试试。

**Comment by phorcys** [comment]
> 串口参数改成 `earlycon=uart,mmio,0x1fe001e0,115200n8 console=ttyS0,115200` 试试。

ok,是 root partition  UUID=xxxx无法找到的问题， clfs没有initrd，所以amdgpu没有加载，console出不来
问题我关闭了

**Comment by donmor** [comment]
话说实机的话不是有完整的loongnix desktop/server来着吗，为什么还弄clfs镜像啊

**Comment by donmor** [comment]
对了老哥能不能试试编译palemoon浏览器:)
