### ISSUE TITLE
关于qemu搭配debootstrap使用的问题

### ISSUE THREAD

**Issue by xeric-w** [loongson/build-tools#19]
Hi

我想用qemu搭一个loongnix的最小系统，以便chroot进去编译我的程序，避免交叉编译的一些麻烦。

步骤：
1. debootstrap --no-check-gpg --variant=minbase --components=main,non-free,contrib --arch=loongarch64 --foreign DaoXiangHu-stable rootfs-loongarch64 http://pkg.loongnix.cn/loongnix/
2. 使用https://github.com/loongson/build-tools/releases/download/2022.05.29/qemu-loongarch64 这版，然后配置好binfmt
3. sudo chroot rootfs-loongarch64 /debootstrap/debootstrap --second-stage

此时报错/bin/sh: error while loading shared libraries: libc.so.6: cannot stat shared object: Error 38

测试环境为Ubuntu 20.04 amd64

有看到这个issue：https://github.com/loongson/build-tools/issues/18 ，但他最后的解法是换工具链，而我是想用loongnix的官方源。

感谢！

**Comment by FreeFlyingSheep** [comment]
@gaosong-loongson

**Comment by gaosong-loongson** [comment]
@xeric-w  将 rootfs中libc.so.6 拷贝到 Ubuntu的 /lib64 路径下.

**Comment by gaosong-loongson** [comment]
@xeric-w 或者用qemu  master 分支编一个qemu-loongarch64.
[qemu-loongarch64-8-10.tar.gz](https://github.com/loongson/build-tools/files/9295740/qemu-loongarch64-8-10.tar.gz)

**Comment by xeric-w** [comment]
> @xeric-w 或者用qemu master 分支编一个qemu-loongarch64. [qemu-loongarch64-8-10.tar.gz](https://github.com/loongson/build-tools/files/9295740/qemu-loongarch64-8-10.tar.gz)

感谢回复！我试了一下您这个，以及我自己也编了一个，现象是一样的。

qemu我也不太懂，但是看了一下代码，我觉得是不是因为loongarh64的qemu没有实现fstat之类的syscall？
因为报错的信息不是找不到libc.so.6，而是cannot **stat**，errno是38（Invalid system call number）。看了qemu的linux-user/loongarch64/syscall_nr.h，相比其他arch，是没有定义#define TARGET_NR_fstat 80，不知道有没有关系。

**Comment by gaosong-loongson** [comment]
@xeric-w 那你用的rootfs_loongarch64应该是用的老工具链，他们可能还没有更新。 新的工具链里没有 79, 80 系统调用了。qemu 已经删了。
[qemu-8-11-add-79-80-syscall.tar.gz](https://github.com/loongson/build-tools/files/9305348/qemu-8-11-add-79-80-syscall.tar.gz)
我加上了79.80 号系统调用， 但我没有试过， 你可以试下， 建议你用新的工具链， 不要从官网上下， 在github 这个里面找， 这个里面的工具都应该是最新的。

**Comment by xeric-w** [comment]
> 

感谢！您修改的这个可以用的。如前所述，我是想chroot到从loognix官网用debootstrap拉下来的rootfs里去，所以这些都不是我自己编译的。那我理解应该是loongnix官方的package build用的还是老工具链？

现在 sudo chroot rootfs-loongarch64/ /bin/bash可以执行了，虽然因为没有配置直接就退出了。

```
$ sudo chroot rootfs-loongarch64/ /bin/bash
I have no name!@my-pc:/# exit
```

吊诡的是没办法chroot进去用dpkg安装deb包，会报这样的错误：

```
$ sudo chroot rootfs-loongarch64/ dpkg -i /test_0.1.0_loongarch64.deb
(Reading database ... 3 files and directories currently installed.)
Preparing to unpack /test_0.1.0_loongarch64.deb ...
dpkg: unrecoverable fatal error, aborting:
 unable to ignore signal Quit before running new base-passwd package pre-installation script: Invalid argument
```

我试了一下，只要deb包有preinst脚本就会出现上面的问题，如果没有preinst脚本就能正常安装（暂时只测试了preinst，没加别的脚本）。preinst脚本里哪怕除了一行#!/bin/bash之外啥都没有也会报错，但如果单独执行sudo chroot rootfs-loongarch64/ /preinst又是正常的。另外虽然报了错，但preinst脚本实际上也被执行过了。感觉就好像是dpkg判断preinst是否成功结束的时候出了啥问题。

不知道您有没有类似的经验...有一种从入门到放弃的感觉 :) 

再谢！

**Comment by gaosong-loongson** [comment]
@xeric-w chroot 退出，rootfs-loongarch64 里面应该是旧世界的环境（4.19内核）（你可以用 tcg-old 分支编一个qemu试下）， 社区qemu master分支 是新世界的（5.19内核）， 你可以用 社区的qemu， 加 clfs， 就是build-tools里面的那个https://github.com/loongson/build-tools/releases/download/2022.08.11/loongarch64-clfs-system-5.5.tar.bz2，可以chroot进去 。这个里面装好了所需的基本工具， 应该能满足你的需求。 至于你后面说的问题， 没有用过那个rootfs， 帮不到你了。

**Comment by xeric-w** [comment]
@gaosong-loongson  使用tcg-old的qemu一切正常了，非常感谢！

```

$ sudo chroot ./rootfs-loongarch64/ /bin/bash
root@my-pc:/# cat /etc/os-release
PRETTY_NAME="Loongnix GNU/Linux 20 (DaoXiangHu)"
NAME="Loongnix GNU/Linux"
VERSION_ID="20"
VERSION="20 (DaoXiangHu)"
VERSION_CODENAME=DaoXiangHu
ID=Loongnix
HOME_URL="https://www.loongnix.cn/"
SUPPORT_URL="https://www.loongnix.cn/"
BUG_REPORT_URL="http://www.loongnix.cn/"

```
