### ISSUE TITLE
The build tool url address changed

### ISSUE THREAD

**Issue by timandy** [loongson/build-tools#25]
Hi @FreeFlyingSheep . I found the qemu tool address has been changed. And the address in  readme does not have `.bin` extension.
https://github.com/loongson/build-tools/blame/750aa562ae8a2a943c06829322bc5862c89ee11e/README.md#L23

Old url : https://github.com/loongson/build-tools/releases/download/2022.09.06/qemu-loongarch64
New url: https://github.com/loongson/build-tools/releases/download/2022.09.06/qemu-loongarch64.bin

This change break my ci action. Can you keep the file address unchanged? Thanks a lot.

**Comment by FreeFlyingSheep** [comment]
I apologize for the inconvenience caused. I have addressed the problem and restored the file address to the previous one. Thank you for your understanding and patience!
