### ISSUE TITLE
Compile kernel and grub failed 

### ISSUE THREAD

**Issue by phorcys** [loongson/build-tools#5]
Using either prebuild toolchain , or custom build toolchain from loongson repo(gcc-12 binutils-2.37 glibc-2.33)

/tmp/cc3MOy9W.s:537: Fatal error: no match insn: li     $r12,0x4
{standard input}:887: Fatal error: no match insn: stl.w $r4,$r24,3

grub2  
source https://github.com/loongarch64/grub/tree/dev-la64

```
In file included from ../../include/grub/relocator.h:25,
                 from ../../include/grub/loongarch64/relocator.h:24,
                 from ../../grub-core/lib/loongarch64/relocator.c:27:
../include/grub/cpu/memory.h: In function ‘grub_map_memory’:
../include/grub/cpu/memory.h:39:50: warning: unused parameter ‘size’ [-Wunused-parameter]
   39 | grub_map_memory (grub_phys_addr_t a, grub_size_t size)
      |                                      ~~~~~~~~~~~~^~~~
/tmp/cc3MOy9W.s: Assembler messages:
/tmp/cc3MOy9W.s:537: Fatal error: no match insn: li     $r12,0x4
Makefile:41604: recipe for target 'lib/loongarch64/relocator_module-relocator.o' failed
```
kernel
source  https://github.com/loongson/linux/tree/loongarch-next

```
:~/mylaos/build/linux-5.13.0$ ARCH=loongarch CROSS_COMPILE=/home/lin/work/loongarch64-linux-gnu-2021-08-03/loongarch64-linux-gnu/bin/loongarch64-linux-gnu- make    
  CALL    scripts/checksyscalls.sh
  CALL    scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  CC      arch/loongarch/kernel/unaligned.o
{standard input}: Assembler messages:
{standard input}:887: Fatal error: no match insn: stl.w $r4,$r24,3
scripts/Makefile.build:272: recipe for target 'arch/loongarch/kernel/unaligned.o' failed
make[2]: *** [arch/loongarch/kernel/unaligned.o] Error 1
scripts/Makefile.build:515: recipe for target 'arch/loongarch/kernel' failed
make[1]: *** [arch/loongarch/kernel] Error 2
Makefile:1847: recipe for target 'arch/loongarch' failed
make: *** [arch/loongarch] Error 2
```

**Comment by yetist** [comment]
grub报错请发在grub仓库那里，新的工具链里面，li指令请换成li.w试试看。

**Comment by xen0n** [comment]
Specific project's problems aside, `li` should not care about bitness; I'm curious why a suffix must be added to such a pseudo-instruction that's supposed to only operate on the whole `GRLEN`.

**Comment by phorcys** [comment]
> grub报错请发在grub仓库那里，新的工具链里面，li指令请换成li.w试试看。

内核的unalign.c 几乎纯c文件，没有嵌入stl.w指令

使用 最新的loongarch64-linux-gnu-08-03.tar.zst 编译 loongarch/linux/loongarch-next

```
$ ARCH=loongarch CROSS_COMPILE=/data/share/la64/loongarch64-linux-gnu-2021-08-03/loongarch64-linux-gnu/bin/loongarch64-linux-gnu- make -j2  
CALL    scripts/atomic/check-atomics.sh  
CALL    scripts/checksyscalls.sh  
CHK     include/generated/compile.h  
CC      arch/loongarch/kernel/unaligned.o  
CC      kernel/bpf/btf.o
{standard input}: Assembler messages:
{standard input}:887: Fatal error: no match insn: stl.w $r4,$r24,3
make[2]: *** [scripts/Makefile.build:271：arch/loongarch/kernel/unaligned.o] 错误 1
make[1]: *** [scripts/Makefile.build:514：arch/loongarch/kernel] 错误 2
make: *** [Makefile:1842：arch/loongarch] 错误 2
```
看起来是gcc产生了ld无法理解的 stl.w

我换了台x86机器，这个问题可以复现：
从 loongson/gcc loongson/binutils-gdb loongson/glibc 编译生成的工具链，
也存在同样问题

编译纯用户态的各种程序目前没有碰到问题，
仅在编译 linux/loongarch-next 和 loongarch64/grub 时候碰到
而使用旧交叉工具链或者loongnix2.0-rc2自带编译环境，kernel和grub2则无问题

**Comment by FreeFlyingSheep** [comment]
> > grub报错请发在grub仓库那里，新的工具链里面，li指令请换成li.w试试看。
> 
> 内核的unalign.c 几乎纯c文件，没有嵌入stl.w指令
> 
> 使用 最新的loongarch64-linux-gnu-08-03.tar.zst 编译 loongarch/linux/loongarch-next
> 
> ```
> $ ARCH=loongarch CROSS_COMPILE=/data/share/la64/loongarch64-linux-gnu-2021-08-03/loongarch64-linux-gnu/bin/loongarch64-linux-gnu- make -j2  
> CALL    scripts/atomic/check-atomics.sh  
> CALL    scripts/checksyscalls.sh  
> CHK     include/generated/compile.h  
> CC      arch/loongarch/kernel/unaligned.o  
> CC      kernel/bpf/btf.o
> {standard input}: Assembler messages:
> {standard input}:887: Fatal error: no match insn: stl.w $r4,$r24,3
> make[2]: *** [scripts/Makefile.build:271：arch/loongarch/kernel/unaligned.o] 错误 1
> make[1]: *** [scripts/Makefile.build:514：arch/loongarch/kernel] 错误 2
> make: *** [Makefile:1842：arch/loongarch] 错误 2
> ```
> 
> 看起来是gcc产生了ld无法理解的 stl.w
> 
> 我换了台x86机器，这个问题可以复现：
> 从 loongson/gcc loongson/binutils-gdb loongson/glibc 编译生成的工具链，
> 也存在同样问题
> 
> 编译纯用户态的各种程序目前没有碰到问题，
> 仅在编译 linux/loongarch-next 和 loongarch64/grub 时候碰到
> 而使用旧交叉工具链或者loongnix2.0-rc2自带编译环境，kernel和grub2则无问题

工具链 [loongarch64-clfs-20210801-cross-tools](https://github.com/loongson/build-tools/releases/download/2021.06.19/loongarch64-clfs-20210801-cross-tools.tar.xz) 已经上传。内核源码也已经更新，请尝试使用该工具链编译最新的内核源码和 Grub2。以上所有软件的编译步骤可以参考 [CLFS For LoongArch64 20210801](https://github.com/sunhaiyong1978/CLFS-for-LoongArch/blob/main/CLFS_For_LoongArch64-20210801.md) 。

**Comment by phorcys** [comment]
> > > grub报错请发在grub仓库那里，新的工具链里面，li指令请换成li.w试试看。
> > 
> > 
> > 内核的unalign.c 几乎纯c文件，没有嵌入stl.w指令
> > 使用 最新的loongarch64-linux-gnu-08-03.tar.zst 编译 loongarch/linux/loongarch-next
> > ```
> > $ ARCH=loongarch CROSS_COMPILE=/data/share/la64/loongarch64-linux-gnu-2021-08-03/loongarch64-linux-gnu/bin/loongarch64-linux-gnu- make -j2  
> > CALL    scripts/atomic/check-atomics.sh  
> > CALL    scripts/checksyscalls.sh  
> > CHK     include/generated/compile.h  
> > CC      arch/loongarch/kernel/unaligned.o  
> > CC      kernel/bpf/btf.o
> > {standard input}: Assembler messages:
> > {standard input}:887: Fatal error: no match insn: stl.w $r4,$r24,3
> > make[2]: *** [scripts/Makefile.build:271：arch/loongarch/kernel/unaligned.o] 错误 1
> > make[1]: *** [scripts/Makefile.build:514：arch/loongarch/kernel] 错误 2
> > make: *** [Makefile:1842：arch/loongarch] 错误 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看起来是gcc产生了ld无法理解的 stl.w
> > 我换了台x86机器，这个问题可以复现：
> > 从 loongson/gcc loongson/binutils-gdb loongson/glibc 编译生成的工具链，
> > 也存在同样问题
> > 编译纯用户态的各种程序目前没有碰到问题，
> > 仅在编译 linux/loongarch-next 和 loongarch64/grub 时候碰到
> > 而使用旧交叉工具链或者loongnix2.0-rc2自带编译环境，kernel和grub2则无问题
> 
> 工具链 [loongarch64-clfs-20210801-cross-tools](https://github.com/loongson/build-tools/releases/download/2021.06.19/loongarch64-clfs-20210801-cross-tools.tar.xz) 已经上传。内核源码也已经更新，请尝试使用该工具链编译最新的内核源码和 Grub2。以上所有软件的编译步骤可以参考 [CLFS For LoongArch64 20210801](https://github.com/sunhaiyong1978/CLFS-for-LoongArch/blob/main/CLFS_For_LoongArch64-20210801.md) 。

换新工具链 ，更新内核源码以后 unaligned.c 没问题了..
不过还是有报错
  CC      arch/loongarch/kernel/vdso.o
arch/loongarch/kernel/vdso.c:54:29: error: ‘vdso_offset_sigreturn’ undeclared here (not in a function)
   54 |         .offset_sigreturn = vdso_offset_sigreturn,
      |                             ^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:271：arch/loongarch/kernel/vdso.o] 错误 1
make[1]: *** [scripts/Makefile.build:514：arch/loongarch/kernel] 错误 2
make: *** [Makefile:1842：arch/loongarch] 错误 2

不过这个和我最初的问题不相关了，这issue我关闭了

**Comment by chhss17** [comment]
> > > > grub报错请发在grub仓库那里，新的工具链里面，li指令请换成li.w试试看。
> > > 
> > > 
> > > 内核的unalign.c 几乎纯c文件，没有嵌入stl.w指令
> > > 使用 最新的loongarch64-linux-gnu-08-03.tar.zst 编译 loongarch/linux/loongarch-next
> > > ```
> > > $ ARCH=loongarch CROSS_COMPILE=/data/share/la64/loongarch64-linux-gnu-2021-08-03/loongarch64-linux-gnu/bin/loongarch64-linux-gnu- make -j2  
> > > CALL    scripts/atomic/check-atomics.sh  
> > > CALL    scripts/checksyscalls.sh  
> > > CHK     include/generated/compile.h  
> > > CC      arch/loongarch/kernel/unaligned.o  
> > > CC      kernel/bpf/btf.o
> > > {standard input}: Assembler messages:
> > > {standard input}:887: Fatal error: no match insn: stl.w $r4,$r24,3
> > > make[2]: *** [scripts/Makefile.build:271：arch/loongarch/kernel/unaligned.o] 错误 1
> > > make[1]: *** [scripts/Makefile.build:514：arch/loongarch/kernel] 错误 2
> > > make: *** [Makefile:1842：arch/loongarch] 错误 2
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看起来是gcc产生了ld无法理解的 stl.w
> > > 我换了台x86机器，这个问题可以复现：
> > > 从 loongson/gcc loongson/binutils-gdb loongson/glibc 编译生成的工具链，
> > > 也存在同样问题
> > > 编译纯用户态的各种程序目前没有碰到问题，
> > > 仅在编译 linux/loongarch-next 和 loongarch64/grub 时候碰到
> > > 而使用旧交叉工具链或者loongnix2.0-rc2自带编译环境，kernel和grub2则无问题
> > 
> > 
> > 工具链 [loongarch64-clfs-20210801-cross-tools](https://github.com/loongson/build-tools/releases/download/2021.06.19/loongarch64-clfs-20210801-cross-tools.tar.xz) 已经上传。内核源码也已经更新，请尝试使用该工具链编译最新的内核源码和 Grub2。以上所有软件的编译步骤可以参考 [CLFS For LoongArch64 20210801](https://github.com/sunhaiyong1978/CLFS-for-LoongArch/blob/main/CLFS_For_LoongArch64-20210801.md) 。
> 
> 换新工具链 ，更新内核源码以后 unaligned.c 没问题了.. 不过还是有报错 CC arch/loongarch/kernel/vdso.o arch/loongarch/kernel/vdso.c:54:29: error: ‘vdso_offset_sigreturn’ undeclared here (not in a function) 54 | .offset_sigreturn = vdso_offset_sigreturn, | ^~~~~~~~~~~~~~~~~~~~~ make[2]: *** [scripts/Makefile.build:271：arch/loongarch/kernel/vdso.o] 错误 1 make[1]: *** [scripts/Makefile.build:514：arch/loongarch/kernel] 错误 2 make: *** [Makefile:1842：arch/loongarch] 错误 2
> 
> 不过这个和我最初的问题不相关了，这issue我关闭了

这个问题是因为下载的gcc中，nm是有问题的，导致在vdso.so.dbg，生成vdso_offset_sigreturn时报错。
