### ISSUE TITLE
如何生成 loongarch 的 32bit 代码

### ISSUE THREAD

**Issue by huangys** [loongson/build-tools#7]
我使用 loongarch64-clfs-20210812-cross-tools ，想要生成 32bit 的目标代码。

试过 
loongarch64-unknown-linux-gnu-gcc -march=loongarch32 a.c
loongarch64-unknown-linux-gnu-gcc: error: unrecognized argument in option ‘-march=loongarch32’

**Comment by sunhaiyong1978** [comment]
现在还不支持32位。
